### ISSUE TITLE
Create README.md as GH organization "landing page"

### ISSUE THREAD

**Issue by mankoff** [nsidc/.github#1]
NSIDC GitHub organization should have a README landing page.

This is a special `.github` repository that allows NSIDC to stylize their GitHub landing page.

> Create a public repository called .github. Once created, add a /profile/README.md. The README will appear on your organization's profile, visible to anyone. 

Documentation: https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

Example: https://github.com/GEUS-Glaciology-and-Climate/ (for an Org; nothing fancy) or https://github.com/rougier/ (for a person; fancy).

**Comment by MattF-NSIDC** [comment]
Neat! I'd love to see this. Happy to help with writing content if needed. I'm really glad someone knows how to navigate all these cool GitHub features :) @jwfuller thoughts on what should go in there?

**Comment by mankoff** [comment]
Edited top ticket to link to https://github.com/rougier/ <-- better example of what you can do with this `landing page`.

**Comment by mankoff** [comment]
Content suggestions:
+ [ ] Logos
+ [ ] Greenland today graphic
+ [ ] Links and DOIs to open science papers (someday)
+ [ ] ???
